"use client";

import Image from "next/image";
import type { NextPage } from "next";
import { useAccount } from "wagmi";
import { Address } from "~~/components/scaffold-eth";

const Home: NextPage = () => {
  const { address: connectedAddress } = useAccount();

  return (
    <>
      <div className="flex items-center flex-col grow pt-10">
        <div className="px-5">
          <h1 className="text-center">
            <span className="block text-2xl mb-2">Welcome to</span>
            <span className="block text-4xl font-bold">GT-NFT</span>
            <span className="block text-xl font-bold">The Art of Division: Where Code, Chance, and Color Collide.</span>
          </h1>
          <div className="flex justify-center items-center space-x-2 flex-col">
            <p className="my-2 font-medium">Connected Address:</p>
            <Address address={connectedAddress} />
          </div>

          <div className="flex items-center flex-col flex-grow pt-10">
            <div className="px-5">
              <h1 className="text-center mb-6">
                <span className="block text-2xl mb-2">Recursive Generative Tiling NFTs</span>
              </h1>
              <div className="flex flex-col items-center justify-center">
                <Image
                  src="/GTNFT.svg"
                  width="400"
                  height="400"
                  alt="gtfnt image"
                  className="rounded-xl border-4 border-primary"
                />
                <div className="max-w-3xl">
                  <p className="mt-8">
                    🎨 Generative Tiling NFT is an on-chain art experiment that explores the beauty of emergent
                    complexity. Each NFT is not just a static image, but a living piece of art generated by a recursive
                    algorithm stored immutably on the Ethereum blockchain.
                  </p>
                  <p className="mt-8">
                    The process begins with a single, unique seed—your token ID. This seed dictates every aspect of the
                    artwork&apos;s &apos;DNA&apos;, from the colour palette to the depth of its recursion. The algorithm
                    then divides the canvas, making a weighted random choice at every step: should it divide further, or
                    should it draw a pattern? The result is a unique, unrepeatable mosaic that can never be created
                    again. Every piece is a one-of-a-kind discovery, born from the elegant collision of mathematics and
                    chance.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="grow bg-base-300 w-full mt-16 px-8 py-12">
          <div className="flex justify-center items-center gap-12 flex-col md:flex-row"></div>
        </div>
      </div>
    </>
  );
};

export default Home;
