"use client";

import Image from "next/image";
import Link from "next/link";
import { Address } from "@scaffold-ui/components";
import type { NextPage } from "next";
import { useAccount } from "wagmi";
import { PhotoIcon, SparklesIcon } from "@heroicons/react/24/outline";
import { useTargetNetwork } from "~~/hooks/scaffold-eth";

const Home: NextPage = () => {
  const { address: connectedAddress } = useAccount();
  const { targetNetwork } = useTargetNetwork();

  return (
    <>
      <div className="flex items-center flex-col grow pt-10">
        <div className="px-5 max-w-3xl w-full">
          <h1 className="text-center">
            <span className="block text-2xl mb-2">Welcome to</span>
            <span className="block text-4xl font-bold">GTNFT</span>
            <span className="block text-xl mt-2 text-base-content/70">
              The Art of Division: Where Code, Chance, and Color Collide.
            </span>
          </h1>

          <div className="flex justify-center items-center space-x-2 flex-col mt-6">
            <p className="my-2 font-medium">Connected Address:</p>
            <Address address={connectedAddress} chain={targetNetwork} />
          </div>
        </div>

        <div className="flex flex-col items-center mt-10 px-5">
          <Image
            src="/GTNFT.svg"
            width={320}
            height={320}
            alt="GTNFT generative art preview"
            loading="eager"
            className="rounded-2xl border-4 border-primary shadow-lg"
          />
          <div className="max-w-2xl mt-8 text-center space-y-4 text-base-content/80">
            <p>
              Each GTNFT is a unique on-chain artwork generated by a recursive tiling algorithm. Your token ID is the
              seed — it determines the palette, depth, and every branch of the composition.
            </p>
            <p>
              Only <span className="font-bold text-primary">3,728</span> available on a bonding curve — each mint
              increases the price by 0.2%.
            </p>
          </div>
        </div>

        <div className="grow bg-base-300 w-full mt-16 px-8 py-12">
          <div className="flex justify-center items-center gap-12 flex-col md:flex-row">
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <PhotoIcon className="h-8 w-8 fill-secondary" />
              <p className="mt-4">
                Browse all minted pieces in the{" "}
                <Link href="/GTNFT" passHref className="link">
                  Gallery
                </Link>
                .
              </p>
            </div>
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <SparklesIcon className="h-8 w-8 fill-secondary" />
              <p className="mt-4">
                View and mint your own in{" "}
                <Link href="/your-GTNFT" passHref className="link">
                  My Collection
                </Link>
                .
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
